//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "App.xaml.h"
#include "MainPage.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "App.g.hpp"
#include "MainPage.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_IsDefault(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->IsDefault);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_IsEnabled(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->IsEnabled);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Kind(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Kind);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_cameras(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->cameras;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_EnclosureLocation(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->EnclosureLocation;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Id(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Id;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Name(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Name;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Properties(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Properties;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Pairing(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Pairing;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_cameras(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->cameras = safe_cast<TValue^>(value);
}

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    bool    isLocalType;
    bool    isSystemType;
    bool    isReturnTypeStub;
    bool    isBindable;
};

TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   2
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   3
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    4, // System.ValueType
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //   4
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //   5
    L"CPPOpenCVTest.MainPage", L"",
    &ActivateType<::CPPOpenCVTest::MainPage>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    true,  false, false, false,
    //   6
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   7
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    1, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   8
    L"Windows.Devices.Enumeration.DeviceInformation", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    1, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //   9
    L"Windows.Devices.Enumeration.EnclosureLocation", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    9, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //  10
    L"Windows.Devices.Enumeration.DeviceInformationKind", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::Windows::Devices::Enumeration::DeviceInformationKind>,
    3, // System.Enum
    9, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //  11
    L"Windows.Devices.Enumeration.DeviceInformationPairing", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    9, 8, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //  12
    L"Windows.Foundation.Collections.IMapView`2<String, Object>", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    9, 8, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //  13
    L"Windows.Foundation.Collections.IVector`1<Windows.Devices.Enumeration.DeviceInformation>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::Windows::Devices::Enumeration::DeviceInformation^>, ::Windows::Devices::Enumeration::DeviceInformation^>, nullptr, nullptr,
    -1,
    9, 8, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    9, 8,::Windows::UI::Xaml::Interop::TypeKind::Custom,
    false, false, false, false,
};

UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      3,   //   8
      3,   //   9
      3,   //  10
      3,   //  11
      4,   //  12
      4,   //  13
      4,   //  14
      4,   //  15
      4,   //  16
      5,   //  17
      5,   //  18
      5,   //  19
      5,   //  20
      5,   //  21
      5,   //  22
      6,   //  23
      6,   //  24
      6,   //  25
      6,   //  26
      6,   //  27
      6,   //  28
      6,   //  29
      7,   //  30
      7,   //  31
      7,   //  32
      7,   //  33
      7,   //  34
      7,   //  35
      7,   //  36
      8,   //  37
      8,   //  38
      8,   //  39
      8,   //  40
      8,   //  41
      8,   //  42
      8,   //  43
      8,   //  44
      8,   //  45
     10,   //  46
     10,   //  47
     10,   //  48
     10,   //  49
     11,   //  50
     11,   //  51
     11,   //  52
     12,   //  53
     12,   //  54
     12,   //  55
     12,   //  56
     12,   //  57
     13,   //  58
     13,   //  59
     13,   //  60
     13,   //  61
     13,   //  62
     13,   //  63
     13,   //  64
     13,   //  65
     13,   //  66
     13,   //  67
     13,   //  68
     13,   //  69
     13,   //  70
     13,   //  71
     13,   //  72
     13,   //  73
     13,   //  74
     13,   //  75
     13,   //  76
     13,   //  77
     13,   //  78
     13,   //  79
     13,   //  80
     13,   //  81
     13,   //  82
     13,   //  83
     13,   //  84
     13,   //  85
     13,   //  86
     13,   //  87
     14,   //  88
};

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

EnumValueInfo EnumValues[] =
{ 
    L"Unknown", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::Unknown,
    L"DeviceInterface", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::DeviceInterface,
    L"DeviceContainer", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::DeviceContainer,
    L"Device", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::Device,
    L"DeviceInterfaceClass", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::DeviceInterfaceClass,
    L"AssociationEndpoint", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::AssociationEndpoint,
    L"AssociationEndpointContainer", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::AssociationEndpointContainer,
    L"AssociationEndpointService", (int) ::Windows::Devices::Enumeration::DeviceInformationKind::AssociationEndpointService,
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

MemberInfo MemberInfos[] = 
{
    //   0 - CPPOpenCVTest.MainPage.cameras
    L"cameras",
    &GetReferenceTypeMember_cameras<::CPPOpenCVTest::MainPage>,
    &SetReferenceTypeMember_cameras<::CPPOpenCVTest::MainPage, ::Windows::Foundation::Collections::IVector<::Windows::Devices::Enumeration::DeviceInformation^>>,
    13, // Windows.Foundation.Collections.IVector`1<Windows.Devices.Enumeration.DeviceInformation>
    -1,
    false, false, false,
    //   1 - Windows.Devices.Enumeration.DeviceInformation.EnclosureLocation
    L"EnclosureLocation",
    &GetReferenceTypeMember_EnclosureLocation<::Windows::Devices::Enumeration::DeviceInformation>,
    nullptr,
    9, // Windows.Devices.Enumeration.EnclosureLocation
    -1,
    true,  false, false,
    //   2 - Windows.Devices.Enumeration.DeviceInformation.Id
    L"Id",
    &GetReferenceTypeMember_Id<::Windows::Devices::Enumeration::DeviceInformation>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //   3 - Windows.Devices.Enumeration.DeviceInformation.IsDefault
    L"IsDefault",
    &GetValueTypeMember_IsDefault<::Windows::Devices::Enumeration::DeviceInformation, ::Platform::Boolean>,
    nullptr,
    2, // Boolean
    -1,
    true,  false, false,
    //   4 - Windows.Devices.Enumeration.DeviceInformation.IsEnabled
    L"IsEnabled",
    &GetValueTypeMember_IsEnabled<::Windows::Devices::Enumeration::DeviceInformation, ::Platform::Boolean>,
    nullptr,
    2, // Boolean
    -1,
    true,  false, false,
    //   5 - Windows.Devices.Enumeration.DeviceInformation.Name
    L"Name",
    &GetReferenceTypeMember_Name<::Windows::Devices::Enumeration::DeviceInformation>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //   6 - Windows.Devices.Enumeration.DeviceInformation.Properties
    L"Properties",
    &GetReferenceTypeMember_Properties<::Windows::Devices::Enumeration::DeviceInformation>,
    nullptr,
    12, // Windows.Foundation.Collections.IMapView`2<String, Object>
    -1,
    true,  false, false,
    //   7 - Windows.Devices.Enumeration.DeviceInformation.Kind
    L"Kind",
    &GetValueTypeMember_Kind<::Windows::Devices::Enumeration::DeviceInformation, ::Windows::Devices::Enumeration::DeviceInformationKind>,
    nullptr,
    10, // Windows.Devices.Enumeration.DeviceInformationKind
    -1,
    true,  false, false,
    //   8 - Windows.Devices.Enumeration.DeviceInformation.Pairing
    L"Pairing",
    &GetReferenceTypeMember_Pairing<::Windows::Devices::Enumeration::DeviceInformation>,
    nullptr,
    11, // Windows.Devices.Enumeration.DeviceInformationPairing
    -1,
    true,  false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    int typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    for (int lastDotIndex = longMemberName->Length(); lastDotIndex >= 0; lastDotIndex--)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
    }
    return nullptr;
}

::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->isSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->isLocalType;
        userType->IsReturnTypeStub = pTypeInfo->isReturnTypeStub;
        userType->IsBindable = pTypeInfo->isBindable;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)
        {
            userType->AddEnumValue(
                ::Platform::StringReference(EnumValues[i].name),
                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

